# Generated by Django 4.2.3 on 2023-08-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managedfile",
            name="file",
            field=models.FileField(upload_to="upload/"),
        ),
    ]
