# Generated by Django 4.1.7 on 2023-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_expenses_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='invoice_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
