# Generated by Django 4.1.7 on 2023-07-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_expenses_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='invoice_number',
            new_name='Ref_Id',
        ),
    ]
