# Generated by Django 4.2.3 on 2023-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_rename_invoice_number_expenses_ref_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="Ref_Id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
