# Generated by Django 4.2.3 on 2023-07-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_expenses_ref_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenses",
            old_name="Ref_Id",
            new_name="ref_id",
        ),
    ]
