# Generated by Django 4.2 on 2023-07-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_stockitems_purchase_ok_stockitems_sale_ok"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockinward",
            name="store_id",
        ),
        migrations.AddField(
            model_name="store",
            name="stock_inward_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.stockinward",
            ),
        ),
    ]
