# Generated by Django 4.2.3 on 2023-07-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_store_stock_inward_id_stockinward_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinward',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor'),
        ),
    ]
