# Generated by Django 4.2 on 2023-08-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_add_default_month_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenses",
            name="store",
        ),
        migrations.RemoveField(
            model_name="stockinward",
            name="store_id",
        ),
        migrations.RemoveField(
            model_name="stockoutward",
            name="store_id",
        ),
        migrations.DeleteModel(
            name="StockAdjustment",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
    ]
