# Generated by Django 4.2 on 2023-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_remove_expenses_store_remove_stockinward_store_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitems",
            name="total_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=100
            ),
        ),
    ]
