# Generated by Django 4.2 on 2023-08-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_remove_stockitems_purchase_ok_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockinward",
            options={"ordering": ["-created_at"]},
        ),
    ]
