# Generated by Django 4.2 on 2023-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_alter_stockinward_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="total_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
