# Generated by Django 4.2 on 2023-08-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_client_total_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
