# Generated by Django 4.2 on 2023-08-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_client_opening_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
