# Generated by Django 4.2.3 on 2023-07-10 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sales_expense_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=django.utils.timezone.now, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sales",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sales",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
