# Generated by Django 4.2.3 on 2023-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_salary_module', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(choices=[('Paid', 'Paid Leave'), ('Unpaid', 'Unpaid Leave')], default='', max_length=10),
        ),
    ]
