# Generated by Django 4.2.3 on 2023-08-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_salary_module', '0004_alter_attendance_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(choices=[('Paid', 'Paid Leave'), ('Unpaid', 'Unpaid Leave'), (None, None)], default=None, max_length=10),
        ),
    ]
