# Generated by Django 4.2 on 2023-08-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0006_alter_attendance_leave_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "earned_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "over_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "attandence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "leaves",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_salary_module.employee",
                    ),
                ),
            ],
        ),
    ]
