# Generated by Django 4.2 on 2023-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0007_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="duration",
            field=models.DateField(default=None),
        ),
    ]
