# Generated by Django 4.2 on 2023-08-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0008_salary_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="net_payable",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="salary",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
