# Generated by Django 4.2 on 2023-08-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0009_salary_net_payable_salary_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
