# Generated by Django 4.2 on 2023-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0010_employee_allowance"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="paid_leaves",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="salary",
            name="unpaid_leaves",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
