# Generated by Django 4.2 on 2023-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0011_salary_paid_leaves_salary_unpaid_leaves"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="duration",
            new_name="month",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="allowance",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="attandence",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="earned_salary",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="leaves",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="net_payable",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="over_time",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="paid_leaves",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="unpaid_leaves",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="working_days",
        ),
        migrations.AddField(
            model_name="salary",
            name="overtime_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="salary",
            name="total_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="salary",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
