# Generated by Django 4.2 on 2023-08-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_salary_module",
            "0012_rename_duration_salary_month_remove_salary_allowance_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="basic_salary",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="salary",
            name="overtime_pay",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="salary",
            name="total_salary",
            field=models.FloatField(default=0),
        ),
    ]
