# Generated by Django 4.2 on 2023-08-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0015_salary_total_working_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="leave_quota",
            field=models.FloatField(default=15),
        ),
    ]
