# Generated by Django 4.2 on 2023-08-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0016_salary_leave_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="monthly_paid_leaves",
            field=models.FloatField(default=0),
        ),
    ]
