# Generated by Django 4.2 on 2023-08-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0017_salary_monthly_paid_leaves"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="monthly_unpaid_leaves",
            field=models.FloatField(default=0),
        ),
    ]
