# Generated by Django 4.2 on 2023-08-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0018_salary_monthly_unpaid_leaves"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="monthly_working_days",
            field=models.FloatField(default=0),
        ),
    ]
