# Generated by Django 4.2 on 2023-08-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0019_salary_monthly_working_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="payable_days",
            field=models.FloatField(default=0),
        ),
    ]
