# Generated by Django 4.2 on 2023-08-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0021_salary_gross_payable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="overtime_pay",
            new_name="over_time",
        ),
        migrations.AddField(
            model_name="salary",
            name="overtime_payable",
            field=models.FloatField(default=0),
        ),
    ]
