# Generated by Django 4.2 on 2023-08-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_salary_module",
            "0022_rename_overtime_pay_salary_over_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="net_payable",
            field=models.FloatField(default=0),
        ),
    ]
