# Generated by Django 4.2.3 on 2023-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0023_salary_net_payable"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="advance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="salary",
            name="total_advance",
            field=models.FloatField(default=0),
        ),
    ]
