# Generated by Django 4.2.3 on 2023-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0024_attendance_advance_salary_total_advance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="advance",
            field=models.FloatField(default=0),
        ),
    ]
