# Generated by Django 4.2 on 2023-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0025_alter_attendance_advance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="extra_day_discription",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_extra_day",
            field=models.BooleanField(default=False),
        ),
    ]
