# Generated by Django 4.2 on 2023-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0026_attendance_extra_day_discription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="extra_day_discription",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_extra_day",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="gross_payable",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="leave_quota",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="monthly_paid_leaves",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="monthly_unpaid_leaves",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="monthly_working_days",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="over_time",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="overtime_payable",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="payable_days",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="total_advance",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="total_salary",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="total_working_days",
        ),
        migrations.AddField(
            model_name="salary",
            name="absent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="advance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="late",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="leaves",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="medical",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="mobile_bils",
            field=models.FloatField(default=0),
        ),
    ]
