# Generated by Django 4.2 on 2023-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_salary_module",
            "0027_remove_attendance_extra_day_discription_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="allowance",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="medical",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="mobile_bils",
        ),
        migrations.AddField(
            model_name="employee",
            name="medical",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="mobile_bils",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="employee",
            name="allowance",
            field=models.FloatField(default=0),
        ),
    ]
