# Generated by Django 4.2 on 2023-08-09 19:13

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_salary_module",
            "0028_remove_salary_allowance_remove_salary_medical_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="month",
            field=month.models.MonthField(default=None),
        ),
    ]
