# Generated by Django 4.2 on 2023-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0029_alter_salary_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="created_date",
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name="salary",
            name="updated_date",
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
