# Generated by Django 4.2 on 2023-08-09 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0030_salary_created_date_salary_updated_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="salary",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="salary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
