# Generated by Django 4.2 on 2023-08-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0031_remove_salary_created_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
