# Generated by Django 4.2 on 2023-08-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0032_delete_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="cnic_number",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="mobile_number_1",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="mobile_number_2",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
