# Generated by Django 4.2 on 2023-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0034_alter_salary_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="over_time",
            field=models.FloatField(default=0),
        ),
    ]
