# Generated by Django 4.2 on 2023-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0035_salary_over_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="over_time_payable",
            field=models.FloatField(default=0),
        ),
    ]
