# Generated by Django 4.2.3 on 2023-08-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0036_salary_over_time_payable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
