# Generated by Django 4.2 on 2023-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0037_alter_employee_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="overtime_rate",
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
        ),
    ]
