# Generated by Django 4.2 on 2023-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_salary_module", "0038_employee_overtime_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="net_advance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="advance_deduction",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salary",
            name="is_absent_deductable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salary",
            name="is_late_deductable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salary",
            name="is_leaves_deductable",
            field=models.BooleanField(default=True),
        ),
    ]
