# Generated by Django 4.2 on 2023-08-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_alter_stockinward_options"),
        ("balance_sheets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transaction",
            new_name="ClientTransaction",
        ),
    ]
