# Generated by Django 4.2 on 2023-08-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0002_rename_transaction_clienttransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clienttransaction",
            name="month",
        ),
    ]
