# Generated by Django 4.2 on 2023-08-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_alter_stockinward_options"),
        ("balance_sheets", "0005_clientbills_clientpayments_delete_clienttransaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientBills",
            new_name="ClientBill",
        ),
        migrations.RenameModel(
            old_name="ClientPayments",
            new_name="ClientPayment",
        ),
    ]
