# Generated by Django 4.2 on 2023-08-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0006_rename_clientbills_clientbill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpayment",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="clientpayment",
            name="paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="clientpayment",
            name="paid_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
