# Generated by Django 4.2 on 2023-08-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0008_clientbill_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientbill",
            old_name="recipient",
            new_name="invoice",
        ),
    ]
