# Generated by Django 4.2 on 2023-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0009_rename_recipient_clientbill_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpayment",
            name="recipient",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
