# Generated by Django 4.2 on 2023-08-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0010_clientpayment_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientpayment",
            old_name="balance",
            new_name="running_balance",
        ),
    ]
