# Generated by Django 4.2 on 2023-08-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_client_total_balance"),
        ("balance_sheets", "0011_rename_balance_clientpayment_running_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("refrence_number", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=200)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.client"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="clientpayment",
            name="client",
        ),
        migrations.DeleteModel(
            name="ClientBill",
        ),
        migrations.DeleteModel(
            name="ClientPayment",
        ),
    ]
