# Generated by Django 4.2 on 2023-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0012_transaction_remove_clientpayment_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="running_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
