# Generated by Django 4.2 on 2023-07-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="salry_amount",
            new_name="salary_amount",
        ),
    ]
