# Generated by Django 4.2.3 on 2023-07-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0002_rename_salry_amount_employee_salary_amount'),
    ]

    operations = [
    ]
