# Generated by Django 4.2.3 on 2023-07-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0003_auto_20230726_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_amount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='salary',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='leave_absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='leave_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_module.employee'),
        ),
    ]
